[package]
name = "wgpu-gpu"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24"
shaderc = "0.8"
wgpu = { version = "24.0", features = ["spirv"] }
pollster = "0.3"
futures-intrusive = "0.4"
bytemuck = "1.7"